// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Bytesize:signIn': typeof import('~icons/bytesize/sign-in')['default']
    'Carbon:aiStatus': typeof import('~icons/carbon/ai-status')['default']
    'Carbon:chartLineData': typeof import('~icons/carbon/chart-line-data')['default']
    'Carbon:dataViewAlt': typeof import('~icons/carbon/data-view-alt')['default']
    'Carbon:researchHintonPlot': typeof import('~icons/carbon/research-hinton-plot')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    'Codicon:home': typeof import('~icons/codicon/home')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    MenuBar: typeof import('./components/MenuBar.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
